auth:
  adminUser: "admin"
  adminPassword: "admin"

externalDatabase:
  host: "postgresql-helix.identity.svc.cluster.local"
  user: "keycloak"
  password: "pg_pass"
  database: "postgresql-helix-db"
  port: 5432

postgresql:
  enabled: false

ingress:
  enabled: true
  ingressClassName: "traefik"
  hostname: "keycloak.helix"
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: "mkcert-ca-issuer"

proxy: edge

extraEnvVars:
  - name: KC_IMPORT_DIR
    value: /opt/keycloak/data/import

extraVolumes:
  - name: helix-theme-volume
    emptyDir: {}

extraVolumeMounts:
  - name: helix-theme-volume
    mountPath: /opt/keycloak/themes

resources:
  requests:
    memory: "1Gi"
    cpu: "200m"
  limits:
    memory: "2Gi"
    cpu: "500m"

readinessProbe:
  httpGet:
    path: /health/ready
    port: 8080
  initialDelaySeconds: 33
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 10

livenessProbe:
  httpGet:
    path: /health/live
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 5
